const seedUsers = [
  {
    firstname: "John",
    lastname: "Doe",
    email: "john.doe@email.com",
    username: "john_doe",
    password: "123456",
    role: "student",
  },
  {
    firstname: "Jane",
    lastname: "Doe",
    email: "jane.doe@email.com",
    username: "jane_doe",
    password: "123456",
    role: "student",
  },
  {
    firstname: "Emily",
    lastname: "Smith",
    email: "emily.smith@email.com",
    username: "emily_smith",
    password: "123456",
    role: "student",
  },
  {
    firstname: "Michael",
    lastname: "Johnson",
    email: "michael.johnson@email.com",
    username: "michael_johnson",
    password: "123456",
    role: "student",
  },
  {
    firstname: "Sarah",
    lastname: "Williams",
    email: "sarah.williams@email.com",
    username: "sarah_williams",
    password: "123456",
    role: "student",
  },
  {
    firstname: "Dr. Alice",
    lastname: "Brown",
    email: "alice.brown@email.com",
    username: "alice_brown",
    password: "123456",
    role: "faculty",
  },
  {
    firstname: "Dr. Bob",
    lastname: "Johnson",
    email: "bob.johnson@email.com",
    username: "bob_johnson",
    password: "123456",
    role: "faculty",
  },
  {
    firstname: "Admin",
    lastname: "User",
    email: "admin.user@email.com",
    username: "admin_user",
    password: "123456",
    role: "admin",
  },
];

module.exports = { seedUsers };
